targets:
  $default:
    builders:
      steroidsGenerator:
        enabled: true
      


builders:
  generators:
    target: ":generators"
    import: "package:generators/generators.dart"
    builder_factories: ["steroidsGenerator"]
    build_extensions: { ".dart": [".steroids.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  