targets:
  $default:
    builders:
      steroidsBuilder:
        enabled: true
        generate_for:
          include:
            - example/lib/core/*



builders:
  generators:
    target: ":generators"
    import: "package:generators/builders.dart"
    builder_factories: ["steroidsBuilder"]
    build_extensions: { ".dart": [".steroids.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  